name: fastfetch
title: fastfetch (unofficial)
version: 2.21.3
license: MIT
#website: 
source-code: https://github.com/fastfetch-cli/fastfetch
issues: https://github.com/thatLeaflet/fastfetch-snap/issues
type: app
icon: snap/gui/fastfetch.png
summary: Like neofetch, but much faster because written mostly in C. 
description: |
  Fastfetch is a neofetch-like tool for fetching system information and displaying them in a pretty way. It is written mainly in C, with performance and customizability in mind.
  
  Note: This is an unofficial repackaging and is not endorsed by the upstream project.

confinement: classic
base: core24
compression: lzo
grade: stable
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [amd64]
    build-for: [arm64]

parts:
  fastfetch:
    plugin: dump
    source:
      - on amd64: https://github.com/fastfetch-cli/fastfetch/releases/download/$SNAPCRAFT_PROJECT_VERSION/fastfetch-linux-amd64.deb
      - on arm64: https://github.com/fastfetch-cli/fastfetch/releases/download/$SNAPCRAFT_PROJECT_VERSION/fastfetch-linux-aarch64.deb
    build-packages:
      - patchelf
    override-prime: |
      craftctl default
      patchelf --force-rpath --set-rpath '$ORIGIN/lib:/snap/core24/current/lib/x86_64-linux-gnu' /root/prime/usr/bin/fastfetch
      patchelf --set-interpreter /snap/core24/current/lib64/ld-linux-x86-64.so.2 /root/prime/usr/bin/fastfetch
      patchelf --force-rpath --set-rpath '$ORIGIN/lib:/snap/core24/current/lib/x86_64-linux-gnu' /root/prime/usr/bin/flashfetch
      patchelf --set-interpreter /snap/core24/current/lib64/ld-linux-x86-64.so.2 /root/prime/usr/bin/flashfetch

apps:
  fastfetch:
    command: /usr/bin/fastfetch
